name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint and Prettier
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build for production
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # Change this if your deployment branch is different
          folder: build

